#!/bin/bash
set -ex
cd $(dirname "$0")
VENV_DIR="./venv"
PYTHON_BIN="$VENV_DIR/bin/python3"
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv --without-pip "$VENV_DIR"
    curl -s https://bootstrap.pypa.io/get-pip.py | "$PYTHON_BIN"
fi
"$PYTHON_BIN" -m pip install --upgrade pip
"$PYTHON_BIN" -m pip install -r requirements.txt
"$PYTHON_BIN" ./main.py
